// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalProveedores.Infrastructure.Persistence;

#nullable disable

namespace PortalProveedores.Infrastructure.Migrations
{
    [DbContext(typeof(PortalProveedoresDbContext))]
    [Migration("20251107150804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioTokens", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CUIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Cotizacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivoPDF_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroCotizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrdenCompraId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.Property<int>("ValidezDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Cotizaciones", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.CotizacionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CotizacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CotizacionItems", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.CotizacionRemitos", b =>
                {
                    b.Property<long>("CotizacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RemitoId")
                        .HasColumnType("bigint");

                    b.HasKey("CotizacionId", "RemitoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("CotizacionRemitos", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Factura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivoPDF_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ConsistenciaCuit")
                        .HasColumnType("bit");

                    b.Property<string>("CuitDestinatario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuitEmisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsConciliadaOK")
                        .HasColumnType("bit");

                    b.Property<bool>("EsValidaAFIP")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstadoProcesamiento")
                        .HasColumnType("int");

                    b.Property<int>("EstadoValidacionAFIP")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F10_VencimientoCAE")
                        .HasColumnType("datetime2");

                    b.Property<string>("F11_ObservacionesAFIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F1_TipoFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F2_PuntoVenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F3_NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("F4_FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("F5_MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("F6_MontoIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("F7_ProveedorCUIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F8_ClienteCUIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F9_CAE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("LetraFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MensajeValidacionAFIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.Property<string>("RazonSocialEmisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoFactura")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalConImpuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImpuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSinImpuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaDetalles", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.FacturaRemitos", b =>
                {
                    b.Property<long>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<long>("RemitoId")
                        .HasColumnType("bigint");

                    b.HasKey("FacturaId", "RemitoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("FacturaRemitos", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descripcion = "Rol A",
                            Name = "AdministrativoCliente",
                            NormalizedName = "ADMINISTRATIVOCLIENTE"
                        },
                        new
                        {
                            Id = 2L,
                            Descripcion = "Rol B",
                            Name = "AdministrativoProveedor",
                            NormalizedName = "ADMINISTRATIVOPROVEEDOR"
                        },
                        new
                        {
                            Id = 3L,
                            Descripcion = "Rol C",
                            Name = "Transportista",
                            NormalizedName = "TRANSPORTISTA"
                        },
                        new
                        {
                            Id = 4L,
                            Descripcion = "Rol D",
                            Name = "RecepcionadorCliente",
                            NormalizedName = "RECEPCIONADORCLIENTE"
                        },
                        new
                        {
                            Id = 5L,
                            Descripcion = "Rol E",
                            Name = "DespachanteProveedor",
                            NormalizedName = "DESPACHANTEPROVEEDOR"
                        });
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<long?>("ProveedorId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfieFotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemoteIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.UsuarioRol", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.NotaDebitoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoAjuste")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Motivo")
                        .HasColumnType("int");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<long?>("UsuarioCreadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("NotasDebitoCredito", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesCompra", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.OrdenCompraItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OrdenCompraId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenCompraItems", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Sku")
                        .IsUnique();

                    b.ToTable("CatalogoProductos", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.ProductoPrecio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVigenciaHasta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioAcordado")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ProductoId", "ProveedorId")
                        .IsUnique();

                    b.ToTable("CatalogoProductoPrecios", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Proveedor", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CUIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Recepcion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DetalleDiferencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaRecepcionista_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaTransportista_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HuboDiferencias")
                        .HasColumnType("bit");

                    b.Property<long>("RemitoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioRecepcionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RemitoId")
                        .IsUnique();

                    b.HasIndex("UsuarioRecepcionId");

                    b.ToTable("Recepciones", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.RecepcionDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CantidadDeclarada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecepcionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecepcionId");

                    b.ToTable("RecepcionDetalles", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Remito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivoPDF_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProveedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Remitos", (string)null);
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.RemitoQRCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<long>("RemitoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CodigoHash")
                        .IsUnique();

                    b.HasIndex("RemitoId");

                    b.ToTable("RemitoQRCodes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Cotizacion", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.CotizacionItem", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cotizacion", "Cotizacion")
                        .WithMany("Items")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.CotizacionRemitos", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Remito", "Remito")
                        .WithMany("CotizacionRemitos")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.FacturaRemitos", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Factura", "Factura")
                        .WithMany("FacturaRemitos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Remito", "Remito")
                        .WithMany()
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.UsuarioRol", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationRole", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.NotaDebitoCredito", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.OrdenCompraItem", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Items")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Producto", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.ProductoPrecio", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Producto", "Producto")
                        .WithMany("PreciosPorProveedor")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Proveedor", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Proveedor")
                        .HasForeignKey("PortalProveedores.Domain.Entities.Proveedor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Recepcion", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Remito", "Remito")
                        .WithOne("Recepcion")
                        .HasForeignKey("PortalProveedores.Domain.Entities.Recepcion", "RemitoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Identity.ApplicationUser", "UsuarioRecepcion")
                        .WithMany()
                        .HasForeignKey("UsuarioRecepcionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Remito");

                    b.Navigation("UsuarioRecepcion");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.RecepcionDetalle", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Recepcion", "Recepcion")
                        .WithMany("Detalles")
                        .HasForeignKey("RecepcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recepcion");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Remito", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PortalProveedores.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.RemitoQRCode", b =>
                {
                    b.HasOne("PortalProveedores.Domain.Entities.Remito", "Remito")
                        .WithMany("QRCodes")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Cotizacion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("FacturaRemitos");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Proveedor");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Producto", b =>
                {
                    b.Navigation("PreciosPorProveedor");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Recepcion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PortalProveedores.Domain.Entities.Remito", b =>
                {
                    b.Navigation("CotizacionRemitos");

                    b.Navigation("QRCodes");

                    b.Navigation("Recepcion");
                });
#pragma warning restore 612, 618
        }
    }
}
